---
- name: Configure users
  hosts: instance1
  vars: 
    users:
      - manuel
      - adriana
  tasks:
    - name: Create users 
      include_tasks: create_users.yml

    - name: Create pictures dirs
      include_tasks: create_dir.yml
      vars:
        dir_name: pictures

